### PR TITLE
Bump to DEV23

### PR DESCRIPTION
**Pull request by cmutel**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cmutel** [comment]
Attention humans: Please don't merge this yet. Thanks!

**Comment by cmutel** [comment]
We don't want to release this to the broader public yet, it has a few issues to fix first, including:

- [ ] https://github.com/brightway-lca/brightway2-data/issues/147
- [ ] https://github.com/brightway-lca/brightway2-data/issues/148

**Comment by cmutel** [comment]
4.0.DEV23 has been yanked from pypi

**Comment by m-rossi** [comment]
Please open a new PR then if there is a new dev release.

**Pull request closed without merging**
